baseurl = "https://fundor333.gitlab.io/"
languageCode = "it"
title = "💻Fundor 333"
theme = "f333-hugo"
disqusShortname = "shortcode-here"

[params]
    Author = "Fundor 333"
    disqus_shortname = "fundor333"
    subtitle = "import antigravity"

[[menu.social]]
  name="facebook"
  url="https://www.facebook.com/fundor333"
  identifier="facebook"
[[menu.social]]
    name="twitter"
    url="https://twitter.com/fundor333"
[[menu.social]]
    name="linkedin"
    url="https://it.linkedin.com/in/matteo-scarpa-78969263"
[[menu.social]]
    name="github"
    url="https://github.com/fundor333"
[[menu.social]]
    name="gitlab"
    url="https://gitlab.com/fundor333"
[[menu.social]]
    name="feed"
    url="index.xml"

[[params.main]]
  name="📓blog"
  url="/categories/blog/"
  text="I miei articoli, ordinati cronologicamente"
[[params.main]]
  name="📚everything"
  url="/post/"
  text="Tutto il materiale del mio blog"
[[params.main]]
  name="️⌨️dev"
  url="/categories/dev/"
  text="Il mio diario di sviluppo"
[[params.main]]
  name="🤵🏻about"
  url="/about/"
  text="Chi sono e cosa faccio"
[[params.main]]
  name="💻project"
  url="/project/"
  text="In sintesi i miei progetti"
[[params.main]]
  name="📌the source"
  url="https://github.com/fundor333/fundor333.github.io"
  text="Il sorgente del sito"
