DefaultContentLanguage = "it"
baseURL = "https://www.fundor333.com/"
disableRSS = false
disqusShortname = "fundor333"
googleAnalytics = "UA-44064318-2"
languageCode = "it-it"
pygmentsUseClassic = true
rssLimit = 10
theme = "f333"
title = "Fundor 333"
[author]
name = "Fundor 333"
[[menu.main]]
identifier = "gem"
name = "resources"
url = "/resource/"
weight = 4
[[menu.main]]
identifier = "code"
name = "source-code"
url = "https://github.com/fundor333/fundor333.com"
weight = 9
[[menu.main]]
identifier = "calendar"
name = "convention"
url = "/event/"
weight = 8
[[menu.main]]
identifier = "sticky-note"
name = "talk"
url = "/talk/"
weight = 7
[[menu.main]]
identifier = "laptop"
name = "project"
url = "/project/"
weight = 6
[[menu.main]]
identifier = "id-card"
name = "about"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "archive"
name = "blog"
url = "/post/"
weight = 1
[[menu.social]]
identifier = "flickr"
name = "flicker"
url = "https://www.flickr.com/people/fundor333/"
weight = 6
[[menu.social]]
identifier = "instagram"
name = "instagram"
url = "https://www.instagram.com/fundor333/"
weight = 5
[[menu.social]]
identifier = "youtube"
name = "youtube"
url = "https://www.youtube.com/channel/UC7SGz-dENnmAueXXjP0Ki2A"
weight = 4
[[menu.social]]
identifier = "twitter"
name = "twitter"
url = "https://twitter.com/fundor333"
weight = 3
[[menu.social]]
identifier = "facebook"
name = "facebook"
url = "https://www.facebook.com/fundor333"
weight = 2
[[menu.social]]
identifier = "github"
name = "github"
url = "https://github.com/fundor333"
weight = 1
[outputs]
section = ["HTML", "RSS", "Calendar"]
[params]
subtitle = "import antigravity"
