baseURL = "https://fundor333.com/"
languageCode = "it-it"
title = "Fundor 333"
theme = "f333"

pygmentsUseClassic = true

rssLimit= 10
disableRSS = false


DefaultContentLanguage = "it"
googleAnalytics = "UA-44064318-2"
disqusShortname = "fundor333"

[outputs]
    section = ["HTML", "RSS", "Calendar"]

[params]
    subtitle = "import antigravity"

[author]
    name = "Fundor 333"

[[menu.social]]
    name ="github"
    identifier= "github"
    weight = 1
    url = "https://github.com/fundor333"

[[menu.social]]
    name ="facebook"
    identifier= "facebook"
    weight = 2
    url =  "https://www.facebook.com/fundor333"

[[menu.social]]
    name ="twitter"
    identifier= "twitter"
    weight = 3
    url = "https://twitter.com/fundor333"
    
[[menu.social]]
    name ="youtube"
    identifier= "youtube"
    weight = 4
    url = "https://www.youtube.com/channel/UC7SGz-dENnmAueXXjP0Ki2A"

[[menu.social]]
    name ="instagram"
    identifier= "instagram"
    weight = 5
    url = "https://www.instagram.com/fundor333/"

[[menu.social]]
    name ="flicker"
    identifier= "flickr"
    weight = 6
    url = "https://www.flickr.com/people/fundor333/"

[[menu.main]]
    name = "blog"
    identifier = "archive"
    weight = 1
    url = "/post/"

[[menu.main]]
    name = "rant"
    identifier = "book"
    weight = 2
    url = "/categories/rant"

[[menu.main]]
    name = "dev"
    identifier = "terminal"
    weight = 3
    url = "/categories/dev/"

[[menu.main]]
    name = "resources"
    identifier = "gem"
    weight = 4
    url = "/resources/"

[[menu.main]]
    name = "about"
    identifier = "id-card"
    weight = 5
    url = "/about/"

[[menu.main]]
    name = "project"
    identifier = "laptop"
    weight = 6
    url = "/project/"

[[menu.main]]
    name = "talk"
    identifier = "sticky-note"
    weight = 7
    url = "/talk/"

[[menu.main]]
    name = "convention"
    identifier = "calendar"
    weight = 8
    url = "/event/"

[[menu.main]]
    name = "source-code"
    identifier = "code"
    weight = 9
    url = "https://github.com/fundor333/fundor333.com"

