DefaultContentLanguage = "it"
baseurl = "https://fundor333.com"
languageCode = "it"
title = "Fundor 333 💻"
theme = "f333-hugo"
disqus_shortname = "fundor333"

[params]
	Author = "Fundor 333"
	disqus_shortname = "fundor333"
	subtitle = "import antigravity"

[[params.social]]
    name="facebook"
	file="facebook.svg"
	color="#3B5998"
	url="https://www.facebook.com/fundor333"

[[params.social]]
    name="mastodon"
	file="mastodon.svg"
	color="#189efc"
	url="https://mastodon.social/@fundor333"

[[params.social]]
    name="twitter"
	file="twitter.svg"
	color="#1DA1F2"
    url="https://twitter.com/fundor333"

[[params.social]]
    name="youtube"
    file="youtube.svg"
    url="https://www.youtube.com/user/Fundor333"

[[params.social]]
    name="instagram"
	file="instagram.svg"
	url="https://www.instagram.com/fundor333/"

[[params.social]]
    name="reddit"
	file="reddit.svg"
	url="https://www.reddit.com/user/fundor333"

[[params.social]]
    name="linkedin"
	file="linkedin.svg"
	color="#0077B5"
    url="https://it.linkedin.com/in/matteo-scarpa-78969263"

[[params.social]]
    name="github"
	file="github.svg"
	color="#181717"
    url="https://github.com/fundor333"

[[params.social]]
    name="gitlab"
	file="gitlab.svg"
	color="#E24329"
    url="https://gitlab.com/fundor333"

[[menu.main]]
	name="📚everything"
	weight= 20
[[menu.main]]
    name="📚archive"
    parent="📚everything"
    url="/post/"
    weight= 10
[[menu.main]]
	name="📓blog"
  	url="/categories/blog/"
  	parent="📚everything"
  	weight= 20
  	text="I miei articoli, ordinati cronologicamente"
[[menu.main]]
	name="👨‍💻dev"
	url="/categories/dev/"
	parent="📚everything"
	weight= 30
	text="Il mio diario di sviluppo"

[[menu.main]]
	name="🔗resources"
  	url="/resources/"
  	text="Link utili che consiglio"
  	weight= 50
	
[[menu.main]]
	name="🤵🏻about"
	url="/about/"
	text="Chi sono e cosa faccio"
	weight= 30
[[menu.main]]
	name="💻project"
	url="/project/"
	text="In sintesi i miei progetti"
	weight= 40
[[menu.main]]
	name="📌the source code"
	url="https://gitlab.com/fundor333/fundor333.gitlab.io"
	text="Il sorgente del sito"
	weight= 70
[[menu.main]]
	name="📰the feed"
	url="https://fundor333.com/post/index.xml"
	text="Ultime news del sito"
	weight= 60