version: 2
jobs:
  build:
    docker:
      - image: fundor333/hugo
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project/
