---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: https://api.netlify.com/build_hooks/5b538c47c6aed60dd6a5e548
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/event
  label: Event
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/resource
  label: Resource
  create: all
  match: "**/*"
- type: directory
  path: content/talk
  label: Talk
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
