---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  talk:
    default_front_matter_template: talk
  post:
    default_front_matter_template: post
  event:
    default_front_matter_template: event
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.38.1
