---
new_page_extension: md
auto_deploy: true
admin_path: 
sections:
- path: content
  label: Pages
  create: all
- path: content/event
  label: Event
  create: all
- path: content/post
  label: Post
  create: all
- path: content/resource
  label: Resource
  create: all
- path: content/talk
  label: Talk
  create: all
upload_dir: static/uploads
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.44'
