---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  talk:
    default_front_matter_template: talk
  post:
    default_front_matter_template: post
  event:
    default_front_matter_template: event
version: 0.38.1
