# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "F333_theme"
license = "MIT"
homepage = "http://siteforthistheme.com/"
min_version = 0.20.6

[author]
  name = "Fundor 333"
  homepage = "http://fundor333.com/"
